name: changelog
permissions: write-all

on:
  push:
    branches:
      - fix/label
    tags:
      - "*"
  workflow_dispatch:

jobs:
  changelog:
    uses: clouddrove/github-shared-workflows/.github/workflows/changelog.yml@master
    secrets: inherit
    with:
      branch: 'master'
    continue-on-error: true